name: auto-merge

on:
  pull_request:
    branches:
      - develop

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Detect Node Version'
        id: detect-node-version
        shell: bash
        run: |
          if [ -f ./.nvmrc ]; then
            nvmrc=$(cat .nvmrc)
          elif [ -f ./.node-version ]; then
            nvmrc=$(cat .node-version)
          else
            nvmrc=0
          fi
          echo "::set-output name=nvmrc::$nvmrc"

      - name: 'Use Node.js ${{ steps.detect-node-version.outputs.nvmrc }}'
        uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: '${{ steps.detect-node-version.outputs.nvmrc }}'
          cache: 'npm'

      - name: 'NPM Test'
        shell: bash
        run: |
          npm version patch
          npx -c 'echo "$npm_package_version"'
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm config set registry https://registry.npmjs.org
          npm config set always-auth true
          sudo mkdir ~/.npm || true
          sudo chown -R $USER:$GROUP ~/.npm || true
          sudo chown -R $USER:$GROUP ~/.config || true
          npm ci
          npm run test
          npm run coverage
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          CODACY_PROJECT_TOKEN:  ${{ secrets.CODACY_PROJECT_TOKEN }}

      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.mytoken }}
